---
name: PHPUnit Tests

on: push

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5

      - name: Install Tests
        run: yarn install:tests

      - name: Composer Install
        run: sudo composer install

      - name: Run unit tests
        run: yarn test:php-coverage-xml

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.39
        if: always()
        with:
          files: ".dev/tests/php/coverage/**/*.xml"

      - name: Code Climate Test Reporter
        uses: aktions/codeclimate-test-reporter@v1
        with:
          codeclimate-test-reporter-id: ${{ secrets.CODE_CLIMATE_TEST_REPORTER_ID }}
          coverageLocations: ${{github.workspace}}/.dev/tests/php/coverage/clover.xml
